# Generated by Django 4.1 on 2022-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_tel', models.CharField(max_length=100)),
            ],
        ),
    ]
