# Generated by Django 4.1 on 2022-10-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEvaluate',
            fields=[
                ('food_evaluate_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_evaluate_text', models.CharField(blank=True, max_length=100, null=True)),
                ('food_evaluate_score', models.IntegerField(blank=True, null=True)),
                ('food_evaluate_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_evaluate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_completed', models.IntegerField()),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_tel', models.CharField(max_length=100)),
                ('user_icon', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'managed': False},
        ),
    ]
